### ISSUE TITLE
[REQUEST] Add the Matter 1.0 Device Types and Application Clusters supported by Google Home Ecosystem

### ISSUE THREAD

**Issue by Hedda** [mfucci/node-matter#132]
Please look into adding support for Matter 1.0 Device Types and Application Clusters supported by Google Home Ecosystem.

https://developers.home.google.com/matter/supported-devices

Use case; Google Nest Hub (2nd gen) opted into Developer Preview firmware will now roll out updates with initial Matter 1.0 support so prioritizing those would mean users will be able to use Google Home app and Google Assistant to control the suppored device types:

https://developers.home.google.com/matter/release-notes

Here is an overview from Google's developers documentation for Matter Device Type conversion to Google Home Ecosystem Type:

Matter Device Type | Application Cluster(s) | Matter Spec | Home Ecosystem Type
-- | -- | -- | -- 
Contact Sensor | Boolean State | 1.0 | Sensor
Dimmable Light | Level Control | 1.0 | Light
Door Lock | Door Lock | 1.0 | Lock
Extended Color Light | Color Control (MoveToHueAndSaturation) | 1.0 | Light
Humidity Sensor | Relative Humidity Measurement | 1.0 | Sensor
Illuminance Sensor | Illuminance Measurement | 1.0 | Sensor
On/Off Light | On/Off | 1.0 | Light
Occupancy Sensor | Occupancy Sensing | 1.0 | Sensor
Plug | Level ControlOn/Off | 1.0 | Outlet
Speaker | Level ControlOn/Off | 1.0 | Speaker
Temperature Sensor | Temperature Measurement | 1.0 | Thermostat
Thermostat | Thermostat | 1.0 | Thermostat
Window Covering | Window Covering | 1.0 | Blinds

**Comment by Apollon77** [comment]
Please create this as "Discussion" because it will be plannable topic.
In fact we are currently working on https://github.com/mfucci/node-matter/discussions/45 to have a basic support for a "switch" devcie at first. After that we plan to add the other clusters too, but this will need time. But also contributions are always welcome (but because of currently happening bigger refactorings and changes because migrating/combining the library in direction of matter.js this needs to be finished first).

**Comment by Hedda** [comment]
> Please create this as "Discussion" because it will be plannable topic.

OK started a new matching discussion here -> https://github.com/mfucci/node-matter/discussions/133

**Comment by Apollon77** [comment]
Thank you!
