### ISSUE TITLE
"Incorrect ack received" error while controlling device via Google Home.

### ISSUE THREAD

**Issue by JimBuzbee** [mfucci/node-matter#179]
Seeing an occasional Incorrect ack received crash controlling my commissioned "device" via Google Home. Log attached. You will see some output from "curl" interspersed with the node-mattter output because I am controlling my physical device via a simple http call using the "-on" and "-off" parameters - works great, very handy to expose control this way.
[GoogleHome.txt](https://github.com/mfucci/node-matter/files/10366934/GoogleHome.txt)

**Comment by Apollon77** [comment]
I experienced a comparanle issue with iOS ... see #181 ...

**Comment by mfucci** [comment]
Thanks for reporting this!

This seems to be an issue in the MessageExchange logic when there is a packet retransmisison:
10:19:20.834 sending id:25313/30302/2011971280 t:1/5 reqAck:true -> original message
10:19:20.844 sending id:25313/30302/2011971280 t:1/5 reqAck:true -> retransmission (not sure why after only 10ms)
10:19:20.857 onMessageReceived id:17869/30302/51617566 t:1/1 acked:2011971280 reqAck:true -> 1st Ack for 2011971280
10:19:20.867 sending id:25313/30302/2011971282 t:1/5 acked:51617566 reqAck:true -> new msg sent
10:19:20.991 onMessageReceived id:17869/30302/51617569 t:0/16 acked:2011971280 -> 2nd Ack for 2011971280, but it was expected to receive an ack on the new message, 2011971282

Two issues here:

1. the re-transmission after 10ms is too fast. The default is 300ms, it might be changed during the setup but seems really too short
2. unexpected acks should be ignored rather than causing a crash

This portion of the code had been written before the Matter specs were released so probably the business logic is not 100% correct....

**Comment by mfucci** [comment]
Here is a MR that hopefully fix this issue: https://github.com/mfucci/node-matter/pull/182

**Comment by mfucci** [comment]
Seems to be fixed by this PR

**Comment by Apollon77** [comment]
I can also ack that
