### ISSUE TITLE
send EADDRNOTAVAIL 224.0.0.251:5353

### ISSUE THREAD

**Issue by Apollon77** [mfucci/node-matter#55]
Hi,

I try my very first steps and use the provided binary (Device.ts). I directly get the following error when I try to execute it:

```
ingof@ApollonMac node-matter % node build/Device.js
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

Error: send EADDRNOTAVAIL 224.0.0.251:5353
    at doSend (node:dgram:705:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:464:18)
    at afterDns (node:dgram:651:5)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -49,
  code: 'EADDRNOTAVAIL',
  syscall: 'send',
  address: '224.0.0.251',
  port: 5353
}
```

When I got the code right the issue is that the broadcast IP is provided in https://github.com/mfucci/node-matter/blob/main/src/net/MdnsServer.ts#L17 but then used in https://github.com/mfucci/node-matter/blob/main/src/net/UdpMulticastServer.ts#L19 as "listeningAddress" and then we end in https://github.com/mfucci/node-matter/blob/main/src/net/node/UdpChannelNode.ts#L18 where he provides that adress to the socket.bind ... 

For receveing or sending multicast stuff that should not be used there, right?

Did I followed the flow correctly ... or is the reson somewhere else?

**Comment by Apollon77** [comment]
Ok, I nained it down to kind of that ... when I remove the listeningAddress property in https://github.com/mfucci/node-matter/blob/main/src/net/UdpMulticastServer.ts#L42 then it works ... 

Should I do a PR?

**Comment by mfucci** [comment]
Thanks!
Weird that this doesn't happen as well on my machine.

I think listeningAddress should actually be interfaceIp to be 100% correct.

Sending an UDP broadcast is not very intuitive in node.js. Here is what needs to be specified:

1. IP / port to broadcast to: this is specified in the send() method
2. IP / port to broadcast from: this is specified as address / port in the bind() method and also used to listen to incoming packets
3. interface to broadcast on: this is specified by calling setMulticastInterface() with the machine IP on that interface after calling bind()

For an MDMS broadcast, here is what should be specified:

1. broadcast to 224.0.0.251 / 5353 (224.0.0.251 is a broadcast address, so the same IP on all interfaces)
2. broadcast from [IP on specified interface] / 5353
3. broadcast on [specified interface]

Current code is clearly incorrect since the broadcast should not be from 224.0.0.251 but from [IP on specified interface].
If listeningAddress, per the node.js doc, the system will try to listen to all ports. It is unclear which IP address will be specified as the from in that case, this is not documented, so I would say it is safer to force it to the correct IP.

Created https://github.com/mfucci/node-matter/pull/59
Can you try if this works?

@jdesai61 : can you also try this fix on your side? I know that you have a configuration with multiple interfaces that this change might break (hopefully not...)

**Comment by Apollon77** [comment]
I tried it locally and works. Thank you! I would not come to that fix ... was still trying to understand the code flow ;-)

**Comment by Apollon77** [comment]
PS: I hope I was not too fast with the merge ;-)

**Comment by jdesai61** [comment]
I tried this out and it didn't change anything for my multi-homed VMs where I test.
